config/routes.rb
Oz::Application.routes.draw do

  get "home/index"
  get "home/profile"
  get "edit/index"

  post "edit/post"
  post "home/create"

  devise_for :teachers, path_names: {sign_in: "login", sign_out: "logout"}

  get "searches/search"
  get "searches/new"
  post "searches/create"
  get "searches/show"
  

  root 'home#index'

end

app/models/money.rb
class Money < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  geocoded_by :address
  after_validation :geocode
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/review.rb
class Review < ActiveRecord::Base
end

app/models/sta.rb
class Sta < ActiveRecord::Base
end

app/models/subject.rb
class Subject < ActiveRecord::Base
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
           geocoded_by :address
  after_validation :geocode
end

app/models/week.rb
class Week < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	$teacher = "hoge"
	$post = Post.find_by(:id => current_teacher[:id])
  end

  def profile
  end
  
  def login
  end
  
  def create
    profile_params
    teacher = Teacher.find_by(:id => current_teacher[:id])
    
    teacher.name = params[:name]
#     teacher.email = params[:email]
    teacher.sex = params[:sex]
    
    if @post = Post.find_by(:id => current_teacher[:id])
    	post.address ="hoge"
   	else
		@post = Post.create(:id => '1')
	end
	
#     teacher.postal_code = params[:postal_code]
#     teacher.address = params[:address]

    if teacher.save
      redirect_to '/home/index'
    else
      render :action => "profile"
    end
  end
  
    private
  def profile_params
    params.permit(:name, :email, :sex, :postal_code, :univ, :address)
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/home/index.html.erb
<h1>My page</h1>
<ul>
  <li><%= current_teacher.email %></li>
  <li><%= current_teacher.name %></li>
  <li><%= current_teacher.sex %></li>
  <li><%= $post %></li>
  <li><%= $teacher %></li>

</ul>
<br/>
<%= link_to 'edit', :controller => "home", :action => "profile" %>

app/views/home/profile.html.erb
<script src="http://ajaxzip3.googlecode.com/svn/trunk/ajaxzip3/ajaxzip3.js" charset="UTF-8"></script>

<h1>プロフィール編集するでな</h1>
<%= form_tag "/home/create" do %>

  <div class="field">
   <%= label :postal_code, :郵便番号 %>
  <input type="text" name="postal_code" size="10" maxlength="8" onKeyUp="AjaxZip3.zip2addr(this,'','address','address');"><br>
    <%= label :address,:住所 %>
  <input name="address" type="text" id="location_address" />
  </div>


  <%= label_tag "名前: " %>
  <%= text_field_tag :name, current_teacher.name %><br />
  <%= label_tag "メールアドレス: " %>
  <%= text_field_tag :email, current_teacher.email %><br />
  <%= label_tag "性別 " %>
  男:
  <% if current_teacher.sex == "male" %>
    <%= radio_button_tag :sex, "male", :checked %>
  <% else %>
    <%= radio_button_tag :sex, "male" %>
  <% end %>
  女:
  <% if current_teacher.sex == "female" %>
    <%= radio_button_tag :sex, "female", :checked %><br />
  <% else %>
    <%= radio_button_tag :sex, "female" %><br />
  <% end %>

  <div class="actions">
  
    <%= submit_tag %>
  </div>



<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Oz</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if teacher_signed_in? %>
<ul>
  <li><%= link_to "ログアウト", destroy_teacher_session_path, method: :delete %></li>
</ul>
<% else %>
  <%= link_to "Sign up", new_teacher_registration_path %> or 
  <%= link_to "Sign in", new_teacher_session_path %>
<% end %>

<%= yield %>

</body>
</html>

app/views/shared/_user_nav.html.erb
		<div id="teacher_nav">
            <% if teacher_signed_in? %>
              Logged in as <strong><%= current_teacher.email %></strong>.
              <%= link_to 'Edit profile', edit_teacher_registration_path %> |
              <%= link_to "Logout", destroy_teacher_session_path, method: :delete %>
            <% else %>
              <%= link_to "Sign up", new_teacher_registration_path %> |
              <%= link_to "Login", new_teacher_session_path %>
            <% end %>
          </div>
         